version: '2.4'

x-database-variables: &database-variables
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employees?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: '@#Andreia32'

services:
    db:
      image: mysql:5.7
      restart: always
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
      - "3306:3306"
      volumes:
      - ./data/sql:/docker-entrypoint-initdb.d
      mem_limit: 512m


    springboot-b2w:
      image: davijuvino/springboot-b2w:0.0.2-SNAPSHOT
      container_name: springboot
      ports:
      - "8080:8080"
      restart: on-failure
      environment:
        <<: *database-variables
      mem_limit: 512m
      depends_on:
      - "db"           
