#|============================================================================|
#| Makefile comandos docker & shell script                - Development       |
#| start container                                                            |
#|============================================================================|

# start:
# 	@docker-compose -f docker-compose.dev.yml up -d 

# down:
# 	@docker-compose -f docker-compose.dev.yml down

# destroy:
# 	@docker-compose -f docker-compose.dev.yml down -v	

# prune:
# 	@docker system prune -af

# stop:
# 	@docker-compose -f docker-compose.dev.yml stop 	
	
# dev:
# 	@docker-compose -f docker-compose.dev.yml up		

# build:
# 	@docker-compose -f docker-compose.dev.yml up --build


